### ISSUE TITLE
Video width and height is 0 on imgur

### ISSUE THREAD

**Issue by rahenri** [dyatlov/go-opengraph#4]
For example: https://imgur.com/r/gifs/h5FZ72Y

I get widht and height 0 for that link, but the size are definitely there in the og tags.

**Comment by dyatlov** [comment]
Hi,

thanks for pointing out on this.

Issue is that `og:video:width/height` are set BEFORE `og:video` tag.
It is invalid according to Opengraph protocol: http://ogp.me/

According to protocol, page can have multiple versions of the same meta tag (http://ogp.me/#array).
And `subproperties` are always related to a `parent property` which is closest to them but defined BEFORE.

I will add a special handling for cases like this but imgur webmasters did a poor job.

**Comment by rahenri** [comment]
Thanks for the quick response.

Indeed, imgur webmasters are not confirming to the standard, thanks for fixing it anyway!

**Comment by dyatlov** [comment]
Fixed, have a look: https://github.com/dyatlov/go-opengraph/commit/471c473a2a4da6f74de29800dbf142f30063e71c
